name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        required: true

env:
  python_version: '3.x'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.release_token }}

      - name: Set author in Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Bump version
        run: |
          python .scripts/bump.py ${{ github.event.inputs.version }}
          git commit --message ${{ github.event.inputs.version }} setup.py
          git tag v${{ github.event.inputs.version }}

      - name: Push release commit
        run: git push --tags origin ${{ github.ref_name }}

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          draft: true
